### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by OLDYTWEBSITE** [MrStudios/DeathRun#15]
### Module

Core (Standard Users)

### Plugin Version

1.2.0

### Server Version

1.20.4 Velocity > Papermc 1.20.4

### Issue Details

The Command Don't Work After My Arena Saved and when i restart, it say "a error has happened with the command" and I'm using the /deathrun command, please test and fix, btw add the rolling stuff thingy in, and add a option to make other players small (only for your clientside) if possible and make it so multiple arenas can be made (and also make the small players stuff config for a config.yaml)

### Confirmation

- [x] I agree to follow this project Contributing & Issues rules.

**Comment by SfenKer** [comment]
More details about this issue is provided in #16, so i marked this issue as duplicate.
