### ISSUE TITLE
[BUG] PACKETS 

### ISSUE THREAD

**Issue by OLDYTWEBSITE** [MrStudios/DeathRun#19]
### Module

Core (Standard Users)

### Plugin Version

1.2.1

### Server Version

Paper 1.20.4

### Issue Details

Large Packets When i join after saving my deathrun area
Edit: its because of [ProtocolSidebar](https://github.com/CatCoderr/ProtocolSidebar)
and can you make it so ppl can turn off they scoreboard in config to disable ProtocolSidebar
or change to diff stuff like Animated Scoreboard, i use simplescore for my deathrun server 

![image](https://github.com/MrStudios/DeathRun/assets/145997493/ee280f90-1830-4b60-9049-44e15dc9d2fa)

### Confirmation

- [X] I agree to follow this project Contributing & Issues rules.

**Comment by SfenKer** [comment]
At this moment i recommend using 1.20.1/2 server version.

**Comment by OLDYTWEBSITE** [comment]
i want to     use 1.20.4 server to stay updated, but I'm trying to do that and it just broke my world stuff, so...

**Comment by SfenKer** [comment]
Resolved in #21
